### ISSUE TITLE
[Semi BUG] Non documented requirement on ascending order for probe calibration

### ISSUE THREAD

**Issue by Tillsten** [kevin-robben/model-fitting#4]
It seems that some part of the software assumes that the probe wavenumber data is ordererd in ascending order

**Comment by kevin-robben** [comment]
Yes. Thanks for pointing that out. I've added some error handling in lines 2207-2214. Enabling compatibility with descending order data would open up a number of other bugs with the program that I'd rather not address right now so I settled for notifying the user if their probe axis needs flipping.
